# We use the 300 csv files created and implement a direct contest against the r codes.

In [1]:
%run -i ~/project/preambles
%run -i ~/project/helper_functions
%run -i ~/project/fitting_functions

In [2]:
# # Global parameters:
number_of_cycles = 500 # how many passes through the training data we go through
number_of_groups = 1 # divide the data set into smaller ones, to make fitting easier.
locations_per_group = 200 # how many locations to observe per group
number_of_locations = number_of_groups * locations_per_group # total locations
number_of_simulations = 300 # for synthetic data, how many optimisation to average over
steps_per_batch = 5
dims = 2  # 2D spatial
p =  3 # how many features

In [3]:
X,Y,true_K, alpha_matrix_true, nu_matrix_true, sigma_matrix_true = Genton_parametrisation(number_of_locations, dims)
ground_truth_df = store_as_df(alpha_matrix_true, nu_matrix_true, sigma_matrix_true)
ground_truth_df

,alpha_matrix_11,nu_matrix_11,sigma_matrix_11,alpha_matrix_12,nu_matrix_12,sigma_matrix_12,alpha_matrix_13,nu_matrix_13,sigma_matrix_13,alpha_matrix_22,nu_matrix_22,sigma_matrix_22,alpha_matrix_23,nu_matrix_23,sigma_matrix_23,alpha_matrix_33,nu_matrix_33,sigma_matrix_33
0,0.01,1.2,1.0,0.0205,1.093,-0.286,0.0263,1.092,-0.181,0.02,0.6,1.0,0.0282,0.99,0.274,0.03,0.3,1.0

In [4]:
estimated_params_df = pd.DataFrame()
distance_K_df = pd.DataFrame()
for _ in range(1,301):
    print(f"data set {_}")
    try:
        # Load the CSV file
        df = pd.read_csv(f'~/project/synthetic_data/realisation_{_}.csv')
        # Extract the spatial coordinates (first and second spatial coordinates)
        X = torch.tensor(df[['0','1']].values[:200], dtype=torch.float64).detach()
        # Prepare Y by reshaping the gene expression levels for each gene
        expression = df['Expression'].values.reshape(200, 3)
        Y = torch.tensor(expression, dtype=torch.float64).detach()
        torch.autograd.set_detect_anomaly(True)
        optimized_marginal_params = optimize_marginal_parameters(X, Y, number_of_groups,  number_of_cycles, steps_per_batch)
        alpha_matrix, nu_matrix, sigma_matrix = optimize_cross_parameters(optimized_marginal_params,X,Y,number_of_groups,number_of_cycles,steps_per_batch)
        estimated_K = compute_matern_covariance(alpha_matrix, nu_matrix, sigma_matrix, X)
        distance_K = torch.norm(true_K - estimated_K)**2 / torch.norm(true_K)**2
        distance_K_df = pd.concat([distance_K_df, pd.DataFrame([distance_K.item()])] ,ignore_index=True)
        estimated_params_df = pd.concat([estimated_params_df, store_as_df(alpha_matrix, nu_matrix, sigma_matrix) ], ignore_index=True)
        # Save the combined DataFrame to a CSV file
        file_path = os.path.expanduser(f'~/project/python_processed_data/synthetic_estimated_parameters_2.csv')
        estimated_params_df.to_csv(file_path, index=False)
    except Exception as e:
        print(e)
        continue
estimated_params_df

data set 1
the values are 1.000, 0.0100000000000000, 1.000
the gradients are 66663.734, 10.9703914524359742, 19.339
the values are 0.900, 0.0000000000000002, 0.900
the gradients are 0.000, 0.0000000000000000, 12.308
the values are 0.833, 0.0000000000000002, 0.804
the gradients are 0.000, 0.0000000000000000, 0.571
the values are 0.781, 0.0000000000000002, 0.727
the gradients are 0.000, 0.0000000000000000, -13.626
the values are 0.739, 0.0000000000000002, 0.703
the gradients are 0.000, 0.0000000000000000, -19.371
the values are 0.703, 0.0000000000000002, 0.719
the gradients are 0.000, 0.0000000000000000, -15.502
the values are 0.672, 0.0000000000000002, 0.754
the gradients are 0.000, 0.0000000000000000, -8.067
the values are 0.645, 0.0000000000000002, 0.794
the gradients are 0.000, 0.0000000000000000, -0.892
the values are 0.621, 0.0000000000000002, 0.831
the gradients are 0.000, 0.0000000000000000, 4.488
the values are 0.600, 0.0000000000000002, 0.858
the gradients are 0.000, 0.0000000000000000, 7.810
the values are 0.581, 0.0000000000000002, 0.871
the gradients are 0.000, 0.0000000000000000, 9.323
the values are 0.564, 0.0000000000000002, 0.871
the gradients are 0.000, 0.0000000000000000, 9.345
the values are 0.549, 0.0000000000000002, 0.860
the gradients are 0.000, 0.0000000000000000, 8.112
the values are 0.535, 0.0000000000000002, 0.841
the gradients are 0.000, 0.0000000000000000, 5.791
the values are 0.523, 0.0000000000000002, 0.817
the gradients are 0.000, 0.0000000000000000, 2.577
the values are 0.512, 0.0000000000000002, 0.793
the gradients are 0.000, 0.0000000000000000, -1.151
the values are 0.502, 0.0000000000000002, 0.772
the gradients are 0.000, 0.0000000000000000, -4.707
the values are 0.493, 0.0000000000000002, 0.758
the gradients are 0.000, 0.0000000000000000, -7.176
the values are 0.484, 0.0000000000000002, 0.755
the gradients are 0.000, 0.0000000000000000, -7.858
the values are 0.477, 0.0000000000000002, 0.761
the gradients are 0.000, 0.0000000000000000, -6.708
the values are 0.470, 0.0000000000000002, 0.774
the gradients are 0.000, 0.0000000000000000, -4.298
the values are 0.463, 0.0000000000000002, 0.791
the gradients are 0.000, 0.0000000000000000, -1.424
the values are 0.458, 0.0000000000000002, 0.808
the gradients are 0.000, 0.0000000000000000, 1.237
the values are 0.452, 0.0000000000000002, 0.822
the gradients are 0.000, 0.0000000000000000, 3.266
the values are 0.448, 0.0000000000000002, 0.831
the gradients are 0.000, 0.0000000000000000, 4.471
the values are 0.443, 0.0000000000000002, 0.833
the gradients are 0.000, 0.0000000000000000, 4.815
the values are 0.439, 0.0000000000000002, 0.830
the gradients are 0.000, 0.0000000000000000, 4.348
the values are 0.436, 0.0000000000000002, 0.821
the gradients are 0.000, 0.0000000000000000, 3.180
the values are 0.433, 0.0000000000000002, 0.810
the gradients are 0.000, 0.0000000000000000, 1.497
the values are 0.430, 0.0000000000000002, 0.797
the gradients are 0.000, 0.0000000000000000, -0.418
the values are 0.427, 0.0000000000000002, 0.786
the gradients are 0.000, 0.0000000000000000, -2.182
the values are 0.424, 0.0000000000000002, 0.779
the gradients are 0.000, 0.0000000000000000, -3.386
the values are 0.422, 0.0000000000000002, 0.777
the gradients are 0.000, 0.0000000000000000, -3.744
the values are 0.420, 0.0000000000000002, 0.780
the gradients are 0.000, 0.0000000000000000, -3.221
the values are 0.418, 0.0000000000000002, 0.787
the gradients are 0.000, 0.0000000000000000, -2.040
the values are 0.417, 0.0000000000000002, 0.796
the gradients are 0.000, 0.0000000000000000, -0.567
the values are 0.415, 0.0000000000000002, 0.805
the gradients are 0.000, 0.0000000000000000, 0.833
the values are 0.414, 0.0000000000000002, 0.812
the gradients are 0.000, 0.0000000000000000, 1.888
the values are 0.412, 0.0000000000000002, 0.816
the gradients are 0.000, 0.0000000000000000, 2.445
the values are 0.411, 0.0000000000000002, 0.816
the gradients are 0.000, 0.0000000000000000, 2.458
the values are 0.410, 0.0000000000000002, 0.813
the gradients are 0.000, 0.0000000000000000, 1.969
the values are 0.409, 0.0000000000000002, 0.807
the gradients are 0.000, 0.0000000000000000, 1.100
the values are 0.408, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.043
the values are 0.407, 0.0000000000000002, 0.794
the gradients are 0.000, 0.0000000000000000, -0.961
the values are 0.407, 0.0000000000000002, 0.789
the gradients are 0.000, 0.0000000000000000, -1.671
the values are 0.406, 0.0000000000000002, 0.788
the gradients are 0.000, 0.0000000000000000, -1.917
the values are 0.405, 0.0000000000000002, 0.789
the gradients are 0.000, 0.0000000000000000, -1.669
the values are 0.405, 0.0000000000000002, 0.793
the gradients are 0.000, 0.0000000000000000, -1.037
the values are 0.404, 0.0000000000000002, 0.798
the gradients are 0.000, 0.0000000000000000, -0.225
the values are 0.404, 0.0000000000000002, 0.803
the gradients are 0.000, 0.0000000000000000, 0.549
the values are 0.403, 0.0000000000000002, 0.807
the gradients are 0.000, 0.0000000000000000, 1.108
the values are 0.403, 0.0000000000000002, 0.809
the gradients are 0.000, 0.0000000000000000, 1.349
the values are 0.403, 0.0000000000000002, 0.808
the gradients are 0.000, 0.0000000000000000, 1.248
the values are 0.402, 0.0000000000000002, 0.805
the gradients are 0.000, 0.0000000000000000, 0.856
the values are 0.402, 0.0000000000000002, 0.802
the gradients are 0.000, 0.0000000000000000, 0.284
the values are 0.402, 0.0000000000000002, 0.798
the gradients are 0.000, 0.0000000000000000, -0.318
the values are 0.402, 0.0000000000000002, 0.795
the gradients are 0.000, 0.0000000000000000, -0.792
the values are 0.401, 0.0000000000000002, 0.793
the gradients are 0.000, 0.0000000000000000, -1.016
the values are 0.401, 0.0000000000000002, 0.794
the gradients are 0.000, 0.0000000000000000, -0.948
the values are 0.401, 0.0000000000000002, 0.796
the gradients are 0.000, 0.0000000000000000, -0.631
the values are 0.401, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.178
the values are 0.401, 0.0000000000000002, 0.802
the gradients are 0.000, 0.0000000000000000, 0.274
the values are 0.401, 0.0000000000000002, 0.804
the gradients are 0.000, 0.0000000000000000, 0.607
the values are 0.401, 0.0000000000000002, 0.805
the gradients are 0.000, 0.0000000000000000, 0.746
the values are 0.400, 0.0000000000000002, 0.804
the gradients are 0.000, 0.0000000000000000, 0.672
the values are 0.400, 0.0000000000000002, 0.803
the gradients are 0.000, 0.0000000000000000, 0.424
the values are 0.400, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.079
the values are 0.400, 0.0000000000000002, 0.798
the gradients are 0.000, 0.0000000000000000, -0.259
the values are 0.400, 0.0000000000000002, 0.797
the gradients are 0.000, 0.0000000000000000, -0.494
the values are 0.400, 0.0000000000000002, 0.796
the gradients are 0.000, 0.0000000000000000, -0.566
the values are 0.400, 0.0000000000000002, 0.797
the gradients are 0.000, 0.0000000000000000, -0.467
the values are 0.400, 0.0000000000000002, 0.798
the gradients are 0.000, 0.0000000000000000, -0.241
the values are 0.400, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.032
the values are 0.400, 0.0000000000000002, 0.802
the gradients are 0.000, 0.0000000000000000, 0.268
the values are 0.400, 0.0000000000000002, 0.802
the gradients are 0.000, 0.0000000000000000, 0.403
the values are 0.400, 0.0000000000000002, 0.802
the gradients are 0.000, 0.0000000000000000, 0.407
the values are 0.400, 0.0000000000000002, 0.802
the gradients are 0.000, 0.0000000000000000, 0.291
the values are 0.400, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.098
the values are 0.400, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.107
the values are 0.400, 0.0000000000000002, 0.798
the gradients are 0.000, 0.0000000000000000, -0.261
the values are 0.400, 0.0000000000000002, 0.798
the gradients are 0.000, 0.0000000000000000, -0.321
the values are 0.400, 0.0000000000000002, 0.798
the gradients are 0.000, 0.0000000000000000, -0.275
the values are 0.400, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.148
the values are 0.400, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.013
the values are 0.400, 0.0000000000000002, 0.801
the gradients are 0.000, 0.0000000000000000, 0.154
the values are 0.400, 0.0000000000000002, 0.801
the gradients are 0.000, 0.0000000000000000, 0.233
the values are 0.400, 0.0000000000000002, 0.801
the gradients are 0.000, 0.0000000000000000, 0.231
the values are 0.400, 0.0000000000000002, 0.801
the gradients are 0.000, 0.0000000000000000, 0.155
the values are 0.400, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.037
the values are 0.400, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.082
the values are 0.400, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.164
the values are 0.400, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.184
the values are 0.400, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.141
the values are 0.400, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.056
the values are 0.400, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.040
the values are 0.399, 0.0000000000000002, 0.801
the gradients are 0.000, 0.0000000000000000, 0.113
the values are 0.399, 0.0000000000000002, 0.801
the gradients are 0.000, 0.0000000000000000, 0.141
the values are 0.399, 0.0000000000000002, 0.801
the gradients are 0.000, 0.0000000000000000, 0.119
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.059
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.016
the values are 0.399, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.078
the values are 0.399, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.108
the values are 0.399, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.096
the values are 0.399, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.053
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.005
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.056
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.082
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.076
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.044
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.042
the values are 0.399, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.063
the values are 0.399, 0.0000000000000002, 0.799
the gradients are 0.000, 0.0000000000000000, -0.059
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.034
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.033
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.049
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.045
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.025
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.027
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.038
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.034
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.017
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.005
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.023
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.030
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.025
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.011
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.006
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.019
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.024
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.018
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.006
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.008
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.017
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.018
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.012
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.008
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.014
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.013
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.007
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.009
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.011
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.009
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.008
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.009
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.006
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.004
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.007
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.006
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.005
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.006
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.004
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.004
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.004
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.002
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.002
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.002
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.003
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.002
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.002
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.002
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.002
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, -0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.000
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800
the gradients are 0.000, 0.0000000000000000, 0.001
the values are 0.399, 0.0000000000000002, 0.800

KeyboardInterrupt:

In [ ]:
histograms_are_plotted = True
df_to_plot = estimated_params_df
%run -i epilogue

In [ ]:
plt.hist(distance_K_df[0])

In [1]:
# After fitting is successful, we are writing down the summary statistics for the various variables.

In [16]:
import pandas as pd

# Assuming df is your DataFrame with the data, and ground_truth_df stores the true values

# Calculate summary statistics: min, Q1, median, mean, Q3, max for each variable
summary_table = df.describe(percentiles=[0.25, 0.5, 0.75]).loc[['min', '25%', '50%', 'mean', '75%', 'max']]

# Adding the ground truth values (assuming ground_truth_df contains the true values as a single row DataFrame)
truths = pd.DataFrame(ground_truth_df.loc[0]).T
truths.index = ['true']

# Concatenate the summary statistics with the true values
comparison_table = pd.concat([truths, summary_table])

# Format the table to show 4 decimal places
comparison_table = comparison_table.map(lambda x: f'{x:.4f}' if isinstance(x, (int, float)) else x)
# Display the table
comparison_table.T

                    true      min      25%      50%     mean      75%     max
alpha_matrix_11   0.0100   0.0000   0.0000   0.0059   0.0169   0.0184  0.3155
nu_matrix_11      1.2000   0.0046   0.9805   1.0177   1.5516   2.0692  4.0056
sigma_matrix_11   1.0000   0.7302   0.9259   0.9877   0.9894   1.0467  1.2536
alpha_matrix_12   0.0205   0.2111   0.9000   0.9044   0.9141   0.9319  1.8288
nu_matrix_12      1.0930   0.0296   1.7924   2.3676   2.5579   3.2452  7.5811
sigma_matrix_12  -0.2860  -0.0713  -0.0000  -0.0000  -0.0019  -0.0000  0.0000
alpha_matrix_13   0.0263   0.2172   0.9000   0.9044   0.9142   0.9325  1.8289
nu_matrix_13      1.0920   0.0935   1.5591   2.0423   2.4547   3.2014  7.7109
sigma_matrix_13  -0.1810  -0.1083  -0.0000  -0.0000  -0.0030  -0.0000  0.0000
alpha_matrix_22   0.0200   0.0000   0.0000   0.0050   0.0141   0.0186  0.3016
nu_matrix_22      0.6000   0.0242   0.9824   1.0175   1.6680   3.4593  4.1098
sigma_matrix_22   1.0000   0.7214   0.9399   0.9980   1.0024   1.0677  1.3416
alpha_matrix_23   0.0282   0.2180   0.9000   0.9045   0.9140   0.9320  1.8288
nu_matrix_23      0.9900   0.0446   1.8011   2.2292   2.5128   3.1719  7.6071
sigma_matrix_23   0.2740  -0.0695  -0.0000  -0.0000  -0.0017  -0.0000  0.0000
alpha_matrix_33   0.0300   0.0000   0.0000   0.0043   0.0164   0.0206  0.3438
nu_matrix_33      0.3000   0.0113   0.9800   1.0169   1.4615   1.8709  3.9635
sigma_matrix_33   1.0000   0.7602   0.9281   0.9979   0.9989   1.0693  1.2406