# We subsample 20 times, with replacement, and check if the fitting results are comparable to each other

In [1]:
%run -i preambles
%run -i helper_functions
%run -i fitting_functions

In [2]:
# # Global parameters:
number_of_cycles = 500 # how many passes through the training data we go through
number_of_groups = 1 # divide the data set into smaller ones, to make fitting easier.
steps_per_batch = 5
dims = 2  # 2D spatial
head = 1000 # how many to down/subsample to.

In [3]:
gene_list = [ "Inha", "Inhba", "Inhbb", "Fst", "Esr1", "Esr2", "Pgr", "Ar", "Cyp19a1", 
    "Cyp17a1", "Cyp11a1", "Lhcgr", "Parm1", "Akr1c18", "Fshr", "Star", "Ptgfr", 
    "Sfrp4", "Acvr1", "Acvr2a", "Acvr2b", "Ghr", "Lhb", "Cga"]
# gene_list = [ "Inha"]
# puck_list = 'all'
puck_list = ['Puck_230517_39'] # the largest puck

adata, X,Y,df=load_data(gene_list=gene_list, head=head, puck_list = puck_list)
df

,x,y,Inha,Inhba,Inhbb,Fst,Esr1,Esr2,Pgr,Ar,...,Fshr,Star,Ptgfr,Sfrp4,Acvr1,Acvr2a,Acvr2b,Ghr,Lhb,Cga
GCAAGACATTGATA-1-2,0.875791,0.665533,3.098373,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
TAAACACTGCAATT-1-2,0.747937,1.165514,0.774593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
GAGNACCTCTTCCA-1-2,0.887622,1.194190,0.774593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.533569,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
CTTCGTAAGGGTTC-1-2,0.689533,1.168430,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.766785,11.494253,10.256411,0.0,0.0,0.0,0.0,0.0,0.0
GCATCTTACATGTT-1-2,0.850364,0.665308,0.774593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AACNCTAGGGTCGA-1-2,0.642177,0.769245,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.766785,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
GTTGGGTACTCGTA-1-2,0.866117,1.287584,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.766785,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
TTCCCGTTTCTGGT-1-2,1.158395,1.547987,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
TTGACGGCTGCTCC-1-2,1.381976,1.371257,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
CGCTAATACCATCT-1-2,0.600735,0.888436,0.774593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.766785,0.000000,5.128205,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
head = 50 # how many locations to consider in the real data set.
estimated_params_df = pd.DataFrame()
for _ in range(20): # sub sampling with replacement the top head rows
    try:
        adata, X,Y,df=load_data(gene_list=gene_list, head=head, puck_list = puck_list)
        torch.autograd.set_detect_anomaly(True)
        optimized_marginal_params = optimize_marginal_parameters(X, Y, number_of_groups,  number_of_cycles, steps_per_batch)
        alpha_matrix, nu_matrix, sigma_matrix = optimize_cross_parameters(optimized_marginal_params,X,Y,number_of_groups,number_of_cycles,steps_per_batch)
        estimated_params_df = pd.concat([estimated_params_df, store_as_df(alpha_matrix, nu_matrix, sigma_matrix) ], ignore_index=True)
    except Exception as e:
        print(e)
        continue
estimated_params_df

Condition failed at epoch 0, halving learning rate. Attempt 1

Condition failed at epoch 0, halving learning rate. Attempt 2

Condition failed at epoch 0, halving learning rate. Attempt 3

Condition failed at epoch 0, halving learning rate. Attempt 4

Condition failed at epoch 0, halving learning rate. Attempt 5

epoch 0 step 1 succeeded with learning rate: 3.125e-05

Learning Rate Halving Log: ['Epoch 0: LR halved at attempt 1', 'Epoch 0: LR halved at attempt 2', 'Epoch 0: LR halved at attempt 3', 'Epoch 0: LR halved at attempt 4', 'Epoch 0: LR halved at attempt 5']

,alpha_matrix_11,nu_matrix_11,sigma_matrix_11,alpha_matrix_12,nu_matrix_12,sigma_matrix_12,alpha_matrix_13,nu_matrix_13,sigma_matrix_13,alpha_matrix_14,...,sigma_matrix_2224,alpha_matrix_2323,nu_matrix_2323,sigma_matrix_2323,alpha_matrix_2324,nu_matrix_2324,sigma_matrix_2324,alpha_matrix_2424,nu_matrix_2424,sigma_matrix_2424
0,2.220446e-16,1.017088,1.592026,0.900526,3.489862,-9.994882e-33,0.900048,3.440006,-9.533091e-33,0.900900,...,-2.274587e-33,0.707556,2.923669,2.220446e-16,1.144845,3.893781,-2.397909e-33,0.707556,2.923669,2.220446e-16
1,1.434579e-02,3.852732,2.520099,0.900237,4.041141,-8.596568e-33,0.900391,5.407200,-4.897023e-32,0.900295,...,-7.840639e-33,0.734378,2.952141,2.220446e-16,1.161738,4.577028,-1.533074e-33,0.734378,2.952141,2.220446e-16
2,2.457918e-02,3.904547,2.522148,0.900206,4.024884,-9.076850e-33,0.900695,3.854027,-7.596740e-33,0.900254,...,-7.986649e-33,0.710012,2.965368,2.220446e-16,1.146379,4.529520,-1.811759e-33,0.710012,2.965368,2.220446e-16
3,2.220446e-16,1.559846,1.933879,0.900102,4.336560,-1.188445e-32,0.900312,4.351503,-1.206635e-32,0.900222,...,-8.208312e-33,0.706764,2.974920,2.220446e-16,1.144402,4.603897,-1.793259e-33,0.706764,2.974920,2.220446e-16
4,1.858031e-02,3.841176,2.536242,0.900333,3.540754,-5.509964e-33,0.900216,5.510309,-5.918736e-32,0.900373,...,-7.973928e-33,0.716359,2.949323,2.220446e-16,1.150338,4.554888,-1.698287e-33,0.716359,2.949323,2.220446e-16
5,1.319039e-01,0.026220,1.952177,0.910613,0.843697,-6.584598e-33,0.917889,0.842522,-6.499608e-33,0.910302,...,-1.294046e-32,0.611496,2.964642,2.220446e-16,1.091334,3.781529,-3.656714e-33,0.611496,2.964642,2.220446e-16
6,8.446677e-03,4.262136,2.504054,0.900219,5.597489,-8.254190e-32,0.900225,3.774291,-7.733191e-33,0.900194,...,-8.747840e-33,0.681599,2.928981,2.220446e-16,1.129039,4.402532,-2.106196e-33,0.681599,2.928981,2.220446e-16
7,1.751741e-02,3.804386,2.535518,0.900223,3.997235,-8.593701e-33,0.900515,5.521408,-6.170657e-32,0.900223,...,-2.032303e-33,0.739954,2.947275,2.220446e-16,1.165238,4.531644,-1.520489e-33,0.739954,2.947275,2.220446e-16
8,2.220446e-16,0.985936,1.592648,0.900183,1.796608,-4.026818e-33,0.901013,1.480360,-4.143073e-33,0.900316,...,-1.051752e-32,0.698526,2.934700,2.220446e-16,1.139415,3.745946,-2.656052e-33,0.698526,2.934700,2.220446e-16
9,1.626890e-01,0.027010,1.979424,0.907521,2.804120,-6.131316e-33,0.907330,2.632753,-5.433411e-33,0.908863,...,-7.303734e-33,0.753425,2.923256,2.220446e-16,1.173739,3.733284,-2.115093e-33,0.753425,2.923256,2.220446e-16
10,2.445854e-01,0.026299,2.344297,0.916631,1.371044,-4.074941e-33,0.917101,0.876351,-6.487897e-33,0.917881,...,-9.513312e-33,0.709478,2.946799,2.220446e-16,1.146151,3.795879,-2.521800e-33,0.709478,2.946799,2.220446e-16
11,7.646870e-02,0.026979,2.474828,0.901744,2.064412,-3.230578e-33,0.901804,3.535996,-5.644843e-33,0.901744,...,-1.781193e-33,0.706018,2.956623,2.220446e-16,1.143975,4.515956,-1.833298e-33,0.706018,2.956623,2.220446e-16
12,2.346417e-02,3.624970,2.473401,0.900257,4.724027,-2.832002e-32,0.900225,3.649638,-7.964146e-33,0.900225,...,-2.173378e-33,0.677330,2.852452,2.220446e-16,1.126457,4.180394,-2.173378e-33,0.677330,2.852452,2.220446e-16
13,1.130399e-02,3.750552,2.445599,0.900076,3.932815,-8.418659e-33,0.900201,5.349329,-5.077364e-32,0.900199,...,-7.354342e-33,0.728542,2.911949,2.220446e-16,1.157949,4.458329,-1.606009e-33,0.728542,2.911949,2.220446e-16
14,5.540382e-02,0.449732,2.420109,0.901895,1.810786,-3.590863e-33,0.901646,3.173153,-4.280209e-33,0.901311,...,-2.112321e-33,0.725445,2.971373,2.220446e-16,1.156007,4.543830,-1.679390e-33,0.725445,2.971373,2.220446e-16
15,1.038709e-01,0.026830,2.001764,0.904057,0.837577,-6.961084e-33,0.904147,0.837540,-6.960193e-33,0.903101,...,-1.051602e-32,0.722098,2.932284,2.220446e-16,1.153959,3.742803,-2.413131e-33,0.722098,2.932284,2.220446e-16
16,1.637514e-02,2.244380,2.525967,0.900168,4.887353,-2.575997e-32,0.904436,2.697935,-3.339524e-33,0.902112,...,-7.542815e-33,0.730095,2.935852,2.220446e-16,1.158937,4.498632,-1.606944e-33,0.730095,2.935852,2.220446e-16
17,4.919797e-02,4.391543,2.530255,0.901542,3.112760,-8.238294e-33,0.900894,4.998936,-9.089293e-32,0.900924,...,-2.404633e-33,0.720498,2.917433,2.220446e-16,1.152960,3.727948,-2.404633e-33,0.720498,2.917433,2.220446e-16
18,1.942183e-02,3.754818,2.525405,0.900628,4.553994,-1.577341e-32,0.900277,5.442594,-5.344083e-32,0.901174,...,-7.272974e-33,0.730978,2.921143,2.220446e-16,1.159491,4.526568,-1.548777e-33,0.730978,2.921143,2.220446e-16
19,1.168637e-01,0.095013,2.391506,0.904533,0.873095,-6.615229e-33,0.904945,0.913762,-6.251816e-33,0.904696,...,-9.428391e-33,0.724825,2.968524,2.220446e-16,1.155616,3.778699,-2.453440e-33,0.724825,2.968524,2.220446e-16